version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sesdashboard-php-fpm
    working_dir: /application
    volumes:
      - ./:/application
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sesdashboard
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: sesdashboard-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  db:
    image: postgres:15-alpine
    container_name: sesdashboard-postgres
    restart: always
    environment:
      POSTGRES_DB: sesdashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

