version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sesdashboard-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sesdashboard
      MYSQL_USER: sesuser
      MYSQL_PASSWORD: sespass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dokploy-network

  php-fpm:
    build: phpdocker/php-fpm
    container_name: sesdashboard-php-fpm
    working_dir: /application
    restart: unless-stopped
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    networks:
      - dokploy-network

  nginx:
    image: nginx:alpine
    container_name: sesdashboard-nginx
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sesdashboard.rule=Host(`admin.salleprivee.ca`)"
      - "traefik.http.routers.sesdashboard.entrypoints=web"
      - "traefik.http.services.sesdashboard.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"

volumes:
  db_data:

networks:
  dokploy-network:
    external: true

