version: "3.8"

services:
  php-fpm:
    build: phpdocker/php-fpm
    container_name: sesdashboard-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    networks:
      - dokploy

  webserver:
    image: nginx:alpine
    container_name: sesdashboard-webserver
    working_dir: /application
    depends_on:
      - php-fpm
    volumes:
      - .:/application
    networks:
      - dokploy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sesdashboard.rule=Host(`admin.salleprivee.ca`)"
      - "traefik.http.routers.sesdashboard.entrypoints=web"
      - "traefik.http.services.sesdashboard.loadbalancer.server.port=80"
    command: >
      /bin/sh -c "echo '
        server {
          listen 80;
          server_name localhost;

          root /application/public;
          index index.php index.html;

          location / {
              try_files \$uri \$uri/ /index.php?\$args;
          }

          location ~ \.php\$ {
              fastcgi_pass sesdashboard-php-fpm:9000;
              fastcgi_index index.php;
              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
              fastcgi_param PHP_VALUE \"error_log=/var/log/nginx/application_php_errors.log\";
              fastcgi_buffers 16 16k;
              fastcgi_buffer_size 32k;
          }

          location = /.htaccess {
              deny all;
              return 404;
          }

          location ~ /\. {
              deny all;
          }
        }
      ' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  dokploy:
    external: true

